---
apiVersion: v1
kind: Service
metadata:
  name: project
  namespace: jgalvin
  labels:
    app: project
spec:
  type: ClusterIP
  ports:
    - port: 8000
      targetPort: 8000
      protocol: TCP
  selector:
    app: project
