---
apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: jgalvin
  labels:
    app: redis
    tier: backend
spec:
  clusterIP: None
  ports:
    - port: 6379
      targetPort: 6379
  selector:
    app: redis
    tier: backend
