---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: jgalvin
bases:
  - ../bases
resources:
  - virtual-service.yaml
patches:
  - path: patch-deployment-project.yaml
    target:
      kind: Deployment
