apiVersion: apps/v1
kind: Deployment
metadata:
  name: camera-deployment
spec:
  selector:
    matchLabels:
      app: camera
  replicas: 1 # tells deployment to run 1 pods matching the template
  template:
    metadata:
      labels:
        app: camera
    spec:
      containers:
      - name: camera
        image: jvgalvin/camera:v2
        ports:
        - containerPort: 1883
        volumeMounts:
        - mountPath: /dev/video0
          name: dev-video0
        securityContext:
          privileged: true
      volumes:
      - name: dev-video0
        hostPath:
          path: /dev/video0
