---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: not-important
  namespace: jgalvin
spec:
  selector:
    matchLabels:
      app: project
  template:
    metadata:
      labels:
        app: project
    spec:
      containers:
        - name: project
          image: project
          resources:
            requests:
              cpu: 500m
              memory: 1Gi
            limits:
              cpu: 750m
              memory: 2Gi
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8000
          readinessProbe:
            httpGet:
              scheme: HTTP
              path: /health
              port: 8000
            initialDelaySeconds: 1
            periodSeconds: 3
          livenessProbe:
            httpGet:
              scheme: HTTP
              path: /health
              port: 8000
            initialDelaySeconds: 15
            periodSeconds: 20
